/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface FateFiPoolInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "CLAIM_WINDOW"
      | "admin"
      | "claim"
      | "claimRefund"
      | "currentDay"
      | "days_"
      | "getDayInfo"
      | "getUserStake"
      | "isDayRefundable"
      | "resolve"
      | "setAdmin"
      | "setStakeAmount"
      | "stake"
      | "stakeAmount"
      | "stakes"
      | "sweepDust"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Claimed"
      | "DayRefundable"
      | "DayResolved"
      | "NewDay"
      | "Refunded"
      | "Staked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "CLAIM_WINDOW",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(functionFragment: "claim", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "claimRefund",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "currentDay",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "days_", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "getDayInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserStake",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isDayRefundable",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "resolve",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setStakeAmount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "stake", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "stakeAmount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "stakes",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sweepDust",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "CLAIM_WINDOW",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimRefund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "currentDay", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "days_", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getDayInfo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getUserStake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isDayRefundable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "resolve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setAdmin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setStakeAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stake", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "stakeAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stakes", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sweepDust", data: BytesLike): Result;
}

export namespace ClaimedEvent {
  export type InputTuple = [
    user: AddressLike,
    dayId: BigNumberish,
    payout: BigNumberish
  ];
  export type OutputTuple = [user: string, dayId: bigint, payout: bigint];
  export interface OutputObject {
    user: string;
    dayId: bigint;
    payout: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DayRefundableEvent {
  export type InputTuple = [dayId: BigNumberish, totalPool: BigNumberish];
  export type OutputTuple = [dayId: bigint, totalPool: bigint];
  export interface OutputObject {
    dayId: bigint;
    totalPool: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DayResolvedEvent {
  export type InputTuple = [
    dayId: BigNumberish,
    winner: BigNumberish,
    totalPool: BigNumberish,
    winnerCount: BigNumberish
  ];
  export type OutputTuple = [
    dayId: bigint,
    winner: bigint,
    totalPool: bigint,
    winnerCount: bigint
  ];
  export interface OutputObject {
    dayId: bigint;
    winner: bigint;
    totalPool: bigint;
    winnerCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NewDayEvent {
  export type InputTuple = [dayId: BigNumberish];
  export type OutputTuple = [dayId: bigint];
  export interface OutputObject {
    dayId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RefundedEvent {
  export type InputTuple = [
    user: AddressLike,
    dayId: BigNumberish,
    amount: BigNumberish
  ];
  export type OutputTuple = [user: string, dayId: bigint, amount: bigint];
  export interface OutputObject {
    user: string;
    dayId: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakedEvent {
  export type InputTuple = [
    user: AddressLike,
    dayId: BigNumberish,
    option: BigNumberish,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    dayId: bigint,
    option: bigint,
    amount: bigint
  ];
  export interface OutputObject {
    user: string;
    dayId: bigint;
    option: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FateFiPool extends BaseContract {
  connect(runner?: ContractRunner | null): FateFiPool;
  waitForDeployment(): Promise<this>;

  interface: FateFiPoolInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  CLAIM_WINDOW: TypedContractMethod<[], [bigint], "view">;

  admin: TypedContractMethod<[], [string], "view">;

  claim: TypedContractMethod<[dayId: BigNumberish], [void], "nonpayable">;

  claimRefund: TypedContractMethod<[dayId: BigNumberish], [void], "nonpayable">;

  currentDay: TypedContractMethod<[], [bigint], "view">;

  days_: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, boolean, boolean, boolean, bigint, bigint, bigint] & {
        totalStaked: bigint;
        winningOption: bigint;
        resolved: boolean;
        exists: boolean;
        refundable: boolean;
        resolvedAt: bigint;
        claimedCount: bigint;
        totalClaimed: bigint;
      }
    ],
    "view"
  >;

  getDayInfo: TypedContractMethod<
    [dayId: BigNumberish],
    [
      [
        bigint,
        [bigint, bigint, bigint],
        [bigint, bigint, bigint],
        boolean,
        bigint
      ] & {
        totalStaked: bigint;
        optionTotals: [bigint, bigint, bigint];
        optionCounts: [bigint, bigint, bigint];
        resolved: boolean;
        winningOption: bigint;
      }
    ],
    "view"
  >;

  getUserStake: TypedContractMethod<
    [dayId: BigNumberish, user: AddressLike],
    [
      [boolean, bigint, boolean] & {
        exists: boolean;
        option: bigint;
        claimed: boolean;
      }
    ],
    "view"
  >;

  isDayRefundable: TypedContractMethod<
    [dayId: BigNumberish],
    [boolean],
    "view"
  >;

  resolve: TypedContractMethod<[winner: BigNumberish], [void], "nonpayable">;

  setAdmin: TypedContractMethod<[newAdmin: AddressLike], [void], "nonpayable">;

  setStakeAmount: TypedContractMethod<
    [_stakeAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  stake: TypedContractMethod<[option: BigNumberish], [void], "payable">;

  stakeAmount: TypedContractMethod<[], [bigint], "view">;

  stakes: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [
      [bigint, boolean, boolean] & {
        option: bigint;
        exists: boolean;
        claimed: boolean;
      }
    ],
    "view"
  >;

  sweepDust: TypedContractMethod<
    [dayId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "CLAIM_WINDOW"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "claim"
  ): TypedContractMethod<[dayId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimRefund"
  ): TypedContractMethod<[dayId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "currentDay"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "days_"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, boolean, boolean, boolean, bigint, bigint, bigint] & {
        totalStaked: bigint;
        winningOption: bigint;
        resolved: boolean;
        exists: boolean;
        refundable: boolean;
        resolvedAt: bigint;
        claimedCount: bigint;
        totalClaimed: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDayInfo"
  ): TypedContractMethod<
    [dayId: BigNumberish],
    [
      [
        bigint,
        [bigint, bigint, bigint],
        [bigint, bigint, bigint],
        boolean,
        bigint
      ] & {
        totalStaked: bigint;
        optionTotals: [bigint, bigint, bigint];
        optionCounts: [bigint, bigint, bigint];
        resolved: boolean;
        winningOption: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserStake"
  ): TypedContractMethod<
    [dayId: BigNumberish, user: AddressLike],
    [
      [boolean, bigint, boolean] & {
        exists: boolean;
        option: bigint;
        claimed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isDayRefundable"
  ): TypedContractMethod<[dayId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "resolve"
  ): TypedContractMethod<[winner: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAdmin"
  ): TypedContractMethod<[newAdmin: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setStakeAmount"
  ): TypedContractMethod<[_stakeAmount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stake"
  ): TypedContractMethod<[option: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "stakeAmount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "stakes"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [
      [bigint, boolean, boolean] & {
        option: bigint;
        exists: boolean;
        claimed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "sweepDust"
  ): TypedContractMethod<
    [dayId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "Claimed"
  ): TypedContractEvent<
    ClaimedEvent.InputTuple,
    ClaimedEvent.OutputTuple,
    ClaimedEvent.OutputObject
  >;
  getEvent(
    key: "DayRefundable"
  ): TypedContractEvent<
    DayRefundableEvent.InputTuple,
    DayRefundableEvent.OutputTuple,
    DayRefundableEvent.OutputObject
  >;
  getEvent(
    key: "DayResolved"
  ): TypedContractEvent<
    DayResolvedEvent.InputTuple,
    DayResolvedEvent.OutputTuple,
    DayResolvedEvent.OutputObject
  >;
  getEvent(
    key: "NewDay"
  ): TypedContractEvent<
    NewDayEvent.InputTuple,
    NewDayEvent.OutputTuple,
    NewDayEvent.OutputObject
  >;
  getEvent(
    key: "Refunded"
  ): TypedContractEvent<
    RefundedEvent.InputTuple,
    RefundedEvent.OutputTuple,
    RefundedEvent.OutputObject
  >;
  getEvent(
    key: "Staked"
  ): TypedContractEvent<
    StakedEvent.InputTuple,
    StakedEvent.OutputTuple,
    StakedEvent.OutputObject
  >;

  filters: {
    "Claimed(address,uint256,uint256)": TypedContractEvent<
      ClaimedEvent.InputTuple,
      ClaimedEvent.OutputTuple,
      ClaimedEvent.OutputObject
    >;
    Claimed: TypedContractEvent<
      ClaimedEvent.InputTuple,
      ClaimedEvent.OutputTuple,
      ClaimedEvent.OutputObject
    >;

    "DayRefundable(uint256,uint256)": TypedContractEvent<
      DayRefundableEvent.InputTuple,
      DayRefundableEvent.OutputTuple,
      DayRefundableEvent.OutputObject
    >;
    DayRefundable: TypedContractEvent<
      DayRefundableEvent.InputTuple,
      DayRefundableEvent.OutputTuple,
      DayRefundableEvent.OutputObject
    >;

    "DayResolved(uint256,uint8,uint256,uint256)": TypedContractEvent<
      DayResolvedEvent.InputTuple,
      DayResolvedEvent.OutputTuple,
      DayResolvedEvent.OutputObject
    >;
    DayResolved: TypedContractEvent<
      DayResolvedEvent.InputTuple,
      DayResolvedEvent.OutputTuple,
      DayResolvedEvent.OutputObject
    >;

    "NewDay(uint256)": TypedContractEvent<
      NewDayEvent.InputTuple,
      NewDayEvent.OutputTuple,
      NewDayEvent.OutputObject
    >;
    NewDay: TypedContractEvent<
      NewDayEvent.InputTuple,
      NewDayEvent.OutputTuple,
      NewDayEvent.OutputObject
    >;

    "Refunded(address,uint256,uint256)": TypedContractEvent<
      RefundedEvent.InputTuple,
      RefundedEvent.OutputTuple,
      RefundedEvent.OutputObject
    >;
    Refunded: TypedContractEvent<
      RefundedEvent.InputTuple,
      RefundedEvent.OutputTuple,
      RefundedEvent.OutputObject
    >;

    "Staked(address,uint256,uint8,uint256)": TypedContractEvent<
      StakedEvent.InputTuple,
      StakedEvent.OutputTuple,
      StakedEvent.OutputObject
    >;
    Staked: TypedContractEvent<
      StakedEvent.InputTuple,
      StakedEvent.OutputTuple,
      StakedEvent.OutputObject
    >;
  };
}
