/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { FateFiPool } from "./FateFiPool";
export * as factories from "./factories";
export { FateFiPool__factory } from "./factories/FateFiPool__factory";
